#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill -USR1 -x sxhkd
. "$HOME"/.cache/wal/colors.sh
wal -R
pkill -9 picom
#picom  --experimental-backends &
picom --experimental-backends --blur-method dual_kawase --blur-strength 3 &

#kill
pkill -9 dunst
pkill -9 xautolock
pkill -9 mpd

#run
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
wal-telegram &
dunst &
wdunst &
mpd & 2>/dev/null
flameshot &
#bspc config

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          12 
bspc config border_radius       20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "$color1"
bspc config active_border_color "#000000"
bspc config normal_border_color "#000000"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop center=true state=floating rectangle=500x800+0+0 
bspc rule -a mpv state=floating center=true rectangle=1500x840+0+0
bspc rule -a scrcpy center=true state=floating rectangle=420x840+0+0 
bspc rule -a Zathura state=floating rectangle=508x904+0+0 

xsetroot -cursor_name left_ptr
#xautolock -detectsleep -time 10 -locker i3lock-fancy -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

~/.config/polybar/launch.sh &   

#send notify
notify-send "bspwm booted ⚡"
